
export const buzzwords = [
	"110%", 
	"Action Item", "Agile", "Alignment", "All hands on deck", "At the end of the day",
	"Back to the drawing board", "Ballpark", "Bandwidth", "Bespoke", "Best of Breed", "Best Practices", "Big picture", "Bleeding Edge", "Blockchain", "Blue Sky Thinking", "Boil the Ocean", "Boots on the ground", "Bottom Line", "Brick and Mortar", "Bring to the table", "Brownie points", "Bubble up", 
	"Capacity", "Circle Back", "Cloud", "Codify", "Collaboration", "Core Competency", "Critical Path", "Customer journey", "Cutting Edge",
	"Data-Driven", "Deep Dive", "Disrupt", "Diversity", "Double click", "Drink the Kool-Aid", "Drill Down", "Ducks in a row", "Due Diligence",
	"Ecosystem", "Empower", "End-to-End", "Engagement", "Enterprise", "Equity", "ETA", "Exponential Growth", 
	"Fast Follow", "Feedback Loop", 
	"Game Changer", "Game Plan", "Gamification", "Globalize", "Go Forward", "Granular",
	"Hardball", "Harmonize", "Headwinds", "Heavy Lifting", "Holistic", "Hyperlocal", 
	"Ideate", "Impact", "In my Back Pocket", "In the weeds", "Innovate",
	"KPI", "Keep the Lights On", 
	"Level Set", "Leverage", "Logistics", "Long Tail", "Low-Hanging Fruit",
	"Metrics", "Mind Share", "Mission Critical", "Move the Needle", 
	"Nearshoring", "Network", "Next Gen", "Next Steps", "No-Brainer", 
	"Offshoring", "Omnichannel", "On the Same Page", "On my Radar", "Operationalize", "Optimize", "Organic Growth", "Out of the Box", "Out of Pocket", "Outsourcing", "Over the Top",
	"Pain Point", "Paradigm Shift", "Ping", "Pipeline", "Pivot", "Proactive", "Pushback", "Put a pin in it", "Put on the Back Burner",
	"Quick Win", 
	"Reach Out", "Real Time", "Red Flag", "Reinvent", "Resources", "Return on Investment", "Revisit", "Revolutionize", "Rightshoring", "Roadmap", "Robust", "Rockstar", "ROI",
	"Scalable", "Seamless", "Service Oriented", "Silo", "Single source of truth", "Socialize", "Streamline", "Supercharge", "Sustainable", "Synergy", "Sync", 
	"Table this", "Take this Offline", "Tasked", "Teambuilding", "Think outside the Box", "Thought Leader", "Tightly coupled", "Touchpoint", "Touch Base", "Track record", "Turnkey",
	"User-Centric", "Unpack", "Upsell", "Upskill", 
	"Value Add", "Value Proposition", "Voluntold", "Viral", "Visionary",
	"Walk Back", "War Room", "Webinar", "Wheelhouse", "Win-Win", "Whiteboard", "Workflow", "Work life balance", "World-Class", "Wrap my head around", 
	"X-Factor", 
	"Yardstick", "Yield",
	"Zero Sum Game",
];