import React from "react"
import type { Metadata } from "next";
import { getMetadata } from "@/app/elements/metadata"
/* import "../globals.css"; */

import Header from "@/app/elements/header"
import Hero from "@/app/elements/hero"
import Nav from "@/app/elements/nav"
import Search from '@/app/elements/search'
import Footer from '@/app/elements/footer'

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export const metadata: Metadata = getMetadata({key:"name", value:"Home"})

/* 
      <script defer={true} src="/js/pixelated.head.js" type="text/javascript" charSet="utf-8"></script>
      <script defer={true} src="//s7.addthis.com/js/300/addthis_widget.js" type="text/javascript"></script>
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <title>Pixelated - Brian Whaley</title>
      <meta httpEquiv="content-type" content="text/html; charset=UTF-8" />
      <meta name="description" content="" />
      <meta name="keywords" content="" />
      <meta name="google-site-verification" content="t2yy9wL1bXPiPQjBqDee2BTgpiGQjwVldlfa4X5CQkU" />
      <meta name="google-site-verification" content="l7D0Y_JsgtACBKNCeFAXPe-UWqo13fPTUCWhkmHStZ4" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
      <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />
      <link rel="alternate" href="www.pixelated.tech" hrefLang="en-us" />
      <script defer={true} src="/js/pixelated.js" type="text/javascript"></script>
      <script defer={true} src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
      <link type="text/css" rel="stylesheet/less" href="/css/pixelated.less" />
      <script defer={true} src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.9.0/less.min.js"></script>
      <link rel="manifest" href="/manifest.json" />
    </head>
      <body>
        <header className="grid12">
          <div id="page-header" className="grid12 fixed-header">
            <Header />
          </div>
          <div id="fixed-header-spacer" className="grid12">
            <Hero />
          </div>
          <div id="page-search" className="grid12 noMobile">
            <Search />
          </div>
        </header>
        <nav>
          <Nav />
        </nav>
        <main className="grid12">
          {children} 
        </main>
        <footer className="grid12">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
