// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
	aws_app_analytics: "enable",
	aws_cognito_identity_pool_id: "us-east-2:679fbb04-e555-465a-b480-84e2a0dabbe7",
	aws_cognito_region: "us-east-2",
	aws_content_delivery: "enable",
	aws_content_delivery_bucket: "pixelated-hosting-mobilehub-1506078167",
	aws_content_delivery_bucket_region: "us-east-2",
	aws_content_delivery_cloudfront: "enable",
	aws_content_delivery_cloudfront_domain: "d3edq0m8zykqdj.cloudfront.net",
	aws_mobile_analytics_app_id: "1fa33fced2a74059a711b55881dff0a2",
	aws_mobile_analytics_app_region: "us-east-1",
	aws_project_id: "6af9bfba-5917-46a0-a72b-00a850fd8c8d",
	aws_project_name: "pixelated",
	aws_project_region: "us-east-2",
	aws_resource_name_prefix: "pixelated-mobilehub-1506078167"
};

export default awsmobile;
