/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "pixelated-hosting-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://pixelated-hosting-dev.s3-website.us-east-2.amazonaws.com",
    "aws_app_analytics": "enable",
    "aws_cognito_identity_pool_id": "us-east-2:679fbb04-e555-465a-b480-84e2a0dabbe7",
    "aws_cognito_region": "us-east-2",
    "aws_content_delivery": "enable",
    "aws_content_delivery_cloudfront": "enable",
    "aws_content_delivery_cloudfront_domain": "d3edq0m8zykqdj.cloudfront.net",
    "aws_mobile_analytics_app_id": "1fa33fced2a74059a711b55881dff0a2",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_project_id": "6af9bfba-5917-46a0-a72b-00a850fd8c8d",
    "aws_project_name": "pixelated",
    "aws_resource_name_prefix": "pixelated-mobilehub-1506078167"
};


export default awsmobile;
